/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankminiproject;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author rudan
 */
public class Menu extends javax.swing.JFrame {
    existingCustomer user;
    Connection con;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        greetlbl.setText("Welcome Back, ");
        showBalancelbl.setText("Balance : ");
    }
    public Menu(existingCustomer user,Connection con) {
        this.con = con;
        this.user = user;
        initComponents();
        greetlbl.setText("Welcome Back, " + user.FirstName + " " + user.LastName);
        showBalancelbl.setText("Balance : " + user.Balance);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greetlbl = new javax.swing.JLabel();
        showBalancelbl = new javax.swing.JLabel();
        withdrawalbtn = new javax.swing.JButton();
        transferbtn = new javax.swing.JButton();
        Depositbtn = new javax.swing.JButton();
        LogOutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        greetlbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        greetlbl.setText("Welcome Back, ");

        showBalancelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        showBalancelbl.setText("Balance : ");

        withdrawalbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        withdrawalbtn.setText("Withdrawal");
        withdrawalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalbtnActionPerformed(evt);
            }
        });

        transferbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        transferbtn.setText("Transfer To");
        transferbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferbtnActionPerformed(evt);
            }
        });

        Depositbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Depositbtn.setText("Deposit");
        Depositbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositbtnActionPerformed(evt);
            }
        });

        LogOutbtn.setBackground(new java.awt.Color(255, 255, 255));
        LogOutbtn.setText("Log Out");
        LogOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greetlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showBalancelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOutbtn))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Depositbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawalbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(greetlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showBalancelbl))
                    .addComponent(LogOutbtn))
                .addGap(18, 18, 18)
                .addComponent(withdrawalbtn)
                .addGap(18, 18, 18)
                .addComponent(Depositbtn)
                .addGap(18, 18, 18)
                .addComponent(transferbtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void changeBal() {
        showBalancelbl.setText("Balance : " + user.Balance);
    }    
    
    private void withdrawalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalbtnActionPerformed
        // TODO add your handling code here:
        new Withdrawal(user,con,this).setVisible(true);
    }//GEN-LAST:event_withdrawalbtnActionPerformed

    private void transferbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferbtnActionPerformed
        // TODO add your handling code here:
        new Transfer(user,con,this).setVisible(true);
    }//GEN-LAST:event_transferbtnActionPerformed

    private void DepositbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositbtnActionPerformed
        // TODO add your handling code here:
        new Deposit(user,con,this).setVisible(true);
    }//GEN-LAST:event_DepositbtnActionPerformed

    private void LogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutbtnActionPerformed
        // TODO add your handling code here:
        try {
            new ThankYou().setVisible(true);
            Thread.sleep(2000);
        }
        catch(InterruptedException ie) {}
        System.exit(0);
    }//GEN-LAST:event_LogOutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Depositbtn;
    private javax.swing.JButton LogOutbtn;
    private javax.swing.JLabel greetlbl;
    private javax.swing.JLabel showBalancelbl;
    private javax.swing.JButton transferbtn;
    private javax.swing.JButton withdrawalbtn;
    // End of variables declaration//GEN-END:variables
}
